### ISSUE TITLE
License/citation for the code?

### ISSUE THREAD

**Issue by YunyiShen** [benaug/Jolly-Seber#1]
Thank you for the great implementation! 
I'm trying to use part of the implementation in a project, esp. the sampler for the activity center. Is there a license for the codebase or a citation I might use?

Thanks!!

**Comment by benaug** [comment]
Thanks, Yunyi, and apologies for the delayed response. I only now noticed I had a notification. I'm not sure how best to create a citation. I plan on publishing this in the relatively near future, but maybe there are other options for the meantime. Do you know of a good option?

**Comment by YunyiShen** [comment]
No worries! Thanks for the response and great codebase. 
I've definitely cited GitHub repositories in the past. The thing I'm trying to build using some of your codebase will eventually be published if it ends up publish-worthy but it will not be in the very near future (I'm still prototyping/debugging). How about I cite this repo for now in my note and when you publish/preprint some written up let me know?

**Comment by benaug** [comment]
Sounds good Yunyi, happy that you've found some of this useful!
